server:
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/bootcamp_spring?serverTimezone=America/Bogota
    username: root
    password:
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MariaDB103Dialect